const storeActionType = {
  SET_SELECTED_CATEGORY: 'SET_SELECTED_CATEGORY',
  SET_SELECTED_SUBCATEGORY: 'SET_SELECTED_SUBCATEGORY',
  TOGGLE_CATEGORY_MENU: 'TOGGLE_CATEGORY_MENU',
  CLOSE_CATEGORY_MENU: 'CLOSE_CATEGORY_MENU',
  TOGGLE_MOBILE_MENU: 'TOGGLE_MOBILE_MENU',
  CLOSE_MOBILE_MENU: 'CLOSE_MOBILE_MENU',
  SEARCH_PRODUCT: 'SEARCH_PRODUCT',
  LOADING: 'LOADING',
  TOGGLE_LOGIN_MODAL: 'TOGGLE_LOGIN_MODAL'
};

export default storeActionType;
