const SET_USER_DATA = 'SET_USER_DATA';
const LOGOUT = 'LOGOUT';
const MESSAGE_USER = 'MESSAGE_USER';
const MESSAGE_CLEARING = 'MESSAGE_CLEARING';

export { SET_USER_DATA, LOGOUT, MESSAGE_USER, MESSAGE_CLEARING };
