const GET_PRODUCTS = 'GET_PRODUCTS';
const DELETE_PRODUCT = 'DELETE_PRODUCT';
const INCREASE_QUANTITY_PRODUCT = 'INCREASE_QUANTITY_PRODUCT';
const DECREASE_QUANTITY_PRODUCT = 'DECREASE_QUANTITY_PRODUCT';

export {
  GET_PRODUCTS,
  DELETE_PRODUCT,
  INCREASE_QUANTITY_PRODUCT,
  DECREASE_QUANTITY_PRODUCT
};
