const GET_PRODUCTS = 'GET_PRODUCTS';
const INCREASE_QUANTITY_PRODUCT = 'INCREASE_QUANTITY_PRODUCT';
const DECREASE_QUANTITY_PRODUCT = 'DECREASE_QUANTITY_PRODUCT';

export { GET_PRODUCTS, INCREASE_QUANTITY_PRODUCT, DECREASE_QUANTITY_PRODUCT };
