const GET_PRODUCTS = 'GET_PRODUCTS';
const ADD_PRODUCT = 'ADD_PRODUCT';
const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
const DELETE_PRODUCT = 'DELETE_PRODUCT';
const INCREASE_QUANTITY_PRODUCT = 'INCREASE_QUANTITY_PRODUCT';
const DECREASE_QUANTITY_PRODUCT = 'DECREASE_QUANTITY_PRODUCT';

export {
  GET_PRODUCTS,
  ADD_PRODUCT,
  UPDATE_PRODUCT,
  DELETE_PRODUCT,
  INCREASE_QUANTITY_PRODUCT,
  DECREASE_QUANTITY_PRODUCT
};
